api = "0.7"

[buildpack]
  description = "A buildpack for starting PHP app server start commands"
  homepage = "https://github.com/paketo-buildpacks/php-start"
  id = "paketo-buildpacks/php-start"
  keywords = ["php", "httpd", "nginx"]
  name = "Paketo Buildpack for PHP Start"

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/php-start/blob/main/LICENSE"

[metadata]
  include-files = ["buildpack.toml", "linux/amd64/bin/build", "linux/amd64/bin/detect", "linux/amd64/bin/procmgr-binary", "linux/amd64/bin/run", "linux/arm64/bin/build", "linux/arm64/bin/detect", "linux/arm64/bin/procmgr-binary", "linux/arm64/bin/run"]
  pre-package = "./scripts/build.sh --target linux/amd64 --target linux/arm64"

[[stacks]]
  id = "*"

[[targets]]
  arch = "amd64"
  os = "linux"

[[targets]]
  arch = "arm64"
  os = "linux"
